// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using TournaCore.API.Models.Entities;

namespace TournaCore.API.Data;

public partial class TournaCoreDbContext : DbContext
{
    public TournaCoreDbContext(DbContextOptions<TournaCoreDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<sys_Role> sys_Roles { get; set; }

    public virtual DbSet<sys_User> sys_Users { get; set; }

    public virtual DbSet<trm_Tournament> trm_Tournaments { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<sys_Role>(entity =>
        {
            entity.HasKey(e => e.ID)
                .HasName("PK_sys_Roles_ID")
                .IsClustered(false);

            entity.HasIndex(e => e.ID, "CL_sys_Roles_ID")
                .IsUnique()
                .IsClustered();

            entity.Property(e => e.ID).ValueGeneratedNever();
        });

        modelBuilder.Entity<sys_User>(entity =>
        {
            entity.HasKey(e => e.ID)
                .HasName("PK_sys_Users_ID")
                .IsClustered(false);

            entity.HasIndex(e => e.ID, "CLS_sys_Users_ID")
                .IsUnique()
                .IsClustered();

            entity.Property(e => e.ID).ValueGeneratedNever();

            entity.HasOne(d => d.Role).WithMany(p => p.sys_Users).OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<trm_Tournament>(entity =>
        {
            entity.HasKey(e => e.ID)
                .HasName("PK_trm_Tournaments_ID")
                .IsClustered(false);

            entity.HasIndex(e => e.ID, "CL_trm_Tournaments_ID")
                .IsUnique()
                .IsClustered();

            entity.Property(e => e.ID).ValueGeneratedNever();

            entity.HasOne(d => d.Owner).WithMany(p => p.trm_Tournaments).OnDelete(DeleteBehavior.ClientSetNull);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}