// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TournaCore.API.Models.Entities;

[Index("Name", Name = "UQ_sys_Roles_Name", IsUnique = true)]
public partial class sys_Role
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(50)]
    public string Name { get; set; } = null!;

    [Precision(3)]
    public DateTime CD { get; set; }

    [StringLength(255)]
    public string CU { get; set; } = null!;

    [Precision(3)]
    public DateTime LD { get; set; }

    [StringLength(255)]
    public string LU { get; set; } = null!;

    [InverseProperty("Role")]
    public virtual ICollection<sys_User> sys_Users { get; set; } = new List<sys_User>();
}