// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TournaCore.API.Models.Entities;

[Index("Email", Name = "UNQ_sys_Users_Email", IsUnique = true)]
public partial class sys_User
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(255)]
    public string Email { get; set; } = null!;

    [StringLength(255)]
    [Unicode(false)]
    public string PassHash { get; set; } = null!;

    [StringLength(255)]
    public string CU { get; set; } = null!;

    [Precision(3)]
    public DateTime CD { get; set; }

    [StringLength(255)]
    public string LU { get; set; } = null!;

    [Precision(3)]
    public DateTime LD { get; set; }

    [StringLength(50)]
    public string Username { get; set; } = null!;

    public Guid Role_ID { get; set; }

    [ForeignKey("Role_ID")]
    [InverseProperty("sys_Users")]
    public virtual sys_Role Role { get; set; } = null!;

    [InverseProperty("Owner")]
    public virtual ICollection<trm_Tournament> trm_Tournaments { get; set; } = new List<trm_Tournament>();
}