// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TournaCore.API.Models.Entities;

public partial class trm_State
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    public string Name { get; set; } = null!;

    [StringLength(255)]
    public string CU { get; set; } = null!;

    [Precision(3)]
    public DateTime CD { get; set; }

    [InverseProperty("State")]
    public virtual ICollection<trm_Tournament> trm_Tournaments { get; set; } = new List<trm_Tournament>();
}