// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TournaCore.API.Models.Entities;

[Keyless]
public partial class v_sys_User
{
    public Guid ID { get; set; }

    [StringLength(255)]
    public string Email { get; set; } = null!;

    [StringLength(50)]
    public string Username { get; set; } = null!;

    public Guid Role_ID { get; set; }

    [StringLength(50)]
    public string RoleName { get; set; } = null!;

    [StringLength(255)]
    [Unicode(false)]
    public string PassHash { get; set; } = null!;

    [Precision(3)]
    public DateTime CD { get; set; }

    [StringLength(255)]
    public string CU { get; set; } = null!;

    [Precision(3)]
    public DateTime LD { get; set; }

    [StringLength(255)]
    public string LU { get; set; } = null!;
}